tabWidth: 4
quoteProps: consistent

pluginSearchDirs:
  - "."
plugins:
  - prettier-plugin-svelte

overrides:
  - files: "*.svelte"
    options:
      parser: svelte
  - files: "*.yaml"
    options:
      tabWidth: 2
